In [4]:
import numpy as np
new_array = np.array([1,2,3,4,5])
float_array = np.array([1.1,2.2,3.3,4.4,5.5])
print(new_array)
print(float_array)

[1 2 3 4 5]
[1.1 2.2 3.3 4.4 5.5]


dtype('float64')

In [5]:
new_array.dtype

dtype('int64')

In [6]:
float_array.dtype

dtype('float64')

In [7]:
new_array[:3]

array([1, 2, 3])

In [8]:
float_array[-1]

5.5

In [9]:
boolean_list = []
boolean_list.append(True)
boolean_list.append(False)
print(boolean_list)

[True, False]
