In [1]:
import numpy as np

In [3]:
A = np.array([[7,5,1],[2,3,3],[9,3,4]])

In [4]:
A

array([[7, 5, 1],
       [2, 3, 3],
       [9, 3, 4]])

In [5]:
B = np.array([[77,55,11],[22,33,33],[99,33,44]])

In [6]:
B

array([[77, 55, 11],
       [22, 33, 33],
       [99, 33, 44]])

In [8]:
np.dot(A,B)

array([[ 748,  583,  286],
       [ 517,  308,  253],
       [1155,  726,  374]])

In [9]:
np.linalg.det(A)

95.0

In [10]:
np.linalg.det(B)

126444.99999999993

In [11]:
np.linalg.eig(A)

(array([11.89743928+0.j        ,  1.05128036+2.62292225j,
         1.05128036-2.62292225j]),
 array([[ 0.53746512+0.j        , -0.18744922+0.38979766j,
         -0.18744922-0.38979766j],
        [ 0.37541841+0.j        , -0.12038675-0.56209234j,
         -0.12038675+0.56209234j],
        [ 0.75511076+0.j        ,  0.69460766+0.j        ,
          0.69460766-0.j        ]]))

In [12]:
np.linalg.eig(B)

(array([130.8718321  +0.j        ,  11.56408395+28.85214475j,
         11.56408395-28.85214475j]),
 array([[ 0.53746512+0.j        , -0.18744922+0.38979766j,
         -0.18744922-0.38979766j],
        [ 0.37541841+0.j        , -0.12038675-0.56209234j,
         -0.12038675+0.56209234j],
        [ 0.75511076+0.j        ,  0.69460766+0.j        ,
          0.69460766-0.j        ]]))

In [13]:
np.linalg.eigvals(A)

array([11.89743928+0.j        ,  1.05128036+2.62292225j,
        1.05128036-2.62292225j])

In [14]:
np.linalg.eigvals(B)

array([130.8718321  +0.j        ,  11.56408395+28.85214475j,
        11.56408395-28.85214475j])

In [15]:
np.linalg.inv(A)

array([[ 0.03157895, -0.17894737,  0.12631579],
       [ 0.2       ,  0.2       , -0.2       ],
       [-0.22105263,  0.25263158,  0.11578947]])

In [16]:
np.linalg.inv(B)

array([[ 0.00287081, -0.01626794,  0.01148325],
       [ 0.01818182,  0.01818182, -0.01818182],
       [-0.02009569,  0.02296651,  0.01052632]])

# determinant

In [18]:
A = np.array([[7,5],[3,6]])
np.linalg.det(A)

27.0

# Inverse

In [19]:
A = np.array([[7,5],[3,6]])
np.linalg.inv(A)

array([[ 0.22222222, -0.18518519],
       [-0.11111111,  0.25925926]])